name="Test repo"

[[rats]]
name="help"
version="v1.0"

    [rats.needs]
    test='>= v5.6 & !v6.7'

[[rats]]
name="help"
version="v0.1"

    [rats.needs]
    test='v7'

[[rats]]
name="test"
version="v5"

[[rats]]
name="test"
version="v7"

    [rats.needs]
    help='greater than v0'